### ISSUE TITLE
Tracy panel extension

### ISSUE THREAD

**Issue by peldax** [iPublikuj/mobile-detect#10]
I was just wondering about extending the tracy bar with mobile-detect panel. 

I imagine panel would display some information about detection (current UA, whether header or session was used to determine UA). 

I am aware its not neccassary and I may do it myself when I get some free time.

**Comment by akadlec** [comment]
PR are welcome.

**Comment by peldax** [comment]
@akadlec Ahoj, právě jsem zahájil práci na panelu a narazil jsem na jedno omezení. Měl bych jeden návrh/nápad. 

Používáš knihovnu MobileDetect, která je supr, rozepozná rozdíl mezi mobilem / tabletem a pozná dokonce operační systém mobilních zařízení.

Kdyby ale někdo (např. já) chtěl kromě téhle funcionality i rozpoznat OS nebo prohlížeč i na desktopu, musí tahat další závislost, protože na to je MobileDetect krátká - není na to určená.

Nepřemýšlel jsi nad tím MobileDetect rozšířit / vyměnit (pokud se najde vhodný kandidát) za knihovnu která detekuje i desktopová zařízení?

**Comment by peldax** [comment]
@akadlec nabízí se https://github.com/jenssegers/agent která je právě toto rozšíření mobiledetectu

**Comment by akadlec** [comment]
Jako teoreticky by to šlo, jen co se mě moc nelíbí je, že by už to nebylo `mobile-detect` ale spíše `device-detect` možná by to bylo vhodnější jako další rozšíření případně se závislostí a rozšiřující tohle.

**Comment by peldax** [comment]
Samozřejmě to mě taky napadlo... Je o na tobě, ale nové rozšíření se mi zdá zbytečné. Použil bych nějakou paralelu - webové  prohlížeče jsou taky určené jen na webové stránky a dnes umí otevřít také i PDF.
