### ISSUE TITLE
Při přepnutí deviceView HttpResponse possible problem

### ISSUE THREAD

**Issue by jirinapravnik** [iPublikuj/mobile-detect#2]
Používám, přepnutí pomocí getParametru (tedy http://site.com?device_view={full/mobile/tablet}) a když kdykoli kliknu, tak se mi do error logu uloží tahle notice:

```
PHP User Notice: Possible problem: you are sending a HTTP header while already having some data in output buffer. Try OutputDebugger or start session earlier. in .../application/vendor/nette/http/src/Http/Response.php:316
```

Nikde žádný obsah nevypisuju, session automaticky startuji v configu. Ladenka nic neukládá je to jen v error logu, takže nevím kde pořádně hledat problém...

**Comment by akadlec** [comment]
Mělo by být vyřešho
