### ISSUE TITLE
nette 2.4 compatibility?

### ISSUE THREAD

**Issue by silviustan** [iPublikuj/mobile-detect#8]
Hi,

I just updated to nette 2.4 and I get this error:

PHP User Deprecated: Invoking filters via $template->getMobileDetectService($vars) is deprecated, use ($vars|getMobileDetectService) in .../vendor/latte/latte/src/Latte/Runtime/Template.php:351

Can you help me? :)

**Comment by akadlec** [comment]
Yes, i know about this incopatibility issue. For hot fix you could check [other libraries](https://github.com/iPublikuj/gravatar/blob/master/src/IPub/Gravatar/Latte/Macros.php#L74) I'm gona fix it but right now i'm out of time.

**Comment by akadlec** [comment]
In new dev version is this issue now fixed. New stable release will be soon
