### ISSUE TITLE
null returned by CookieSettings::getDomain()

### ISSUE THREAD

**Issue by JosefRypacek** [iPublikuj/mobile-detect#9]
Ahoj,

po aktualizaci z 1.0.3 na 2.0.0 mi chodí z nette emaily o chybě (viz níže). Problém se mi nasimulovat nepodařilo, nevím tedy kdy uvedený problém nastává. Na webu používám detekci "isMobile". Zkoušel jsem i smazat všechny sessions na serveru což nepomohlo. Popravdě ani netuším kdy a proč se cookies používají (v prohlížeči žádnou nevidím).

Chyba je jasná, funkce vrátí null i když by neměla. Opět zde ale nemám tušení, kde by měla vzít správný string, nikde v kódu jsem jeho přiřazení nenašel...

TypeError: Return value of IPub\MobileDetect\Helpers\CookieSettings::getDomain() must be of the type string, null returned in xxx/vendor/ipub/mobile-detect/src/IPub/MobileDetect/Helpers/CookieSettings.php:116

**Comment by akadlec** [comment]
Hele koukal jsem na to, a byla tam špatná definice return type. Poslední release by toto měl fixnout.

**Comment by JosefRypacek** [comment]
Díky, máš pravdu. Tohle bude fungovat. V Mezičase jsem to nějak dočasně ošetřil a úplně jsem na to zapomněl.
